import {ClerkProvider} from '@clerk/nextjs';
import {ThemeProvider} from '@web/components/ThemeProvider';
import TrpcProvider from '@web/lib/trpc/Provider';
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import {cookies} from 'next/headers';
import './globals.css';
import {Toaster} from 'sonner';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ThemeProvider
					attribute="class"
					defaultTheme="light"
					disableTransitionOnChange
				>
					<ClerkProvider>
						<TrpcProvider cookies={cookies().toString()}>
							{children}
						</TrpcProvider>
					</ClerkProvider>
					<Toaster richColors />
				</ThemeProvider>
			</body>
		</html>
	);
}
